[package]
name = "hyprlaunch"
version = "0.2.1-1"
edition = "2021"
authors = [ "Josh Andrews" ]
license = "GPL-3.0"
description = "A simple, profile-based application launcher for Hyprland"
readme = "README.md"
repository = "https://github.com/lehkost16/hyprlaunch"
keywords = [ "hyprland", "profile", "launcher", "tui" ]

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
ratatui = "0.26"
crossterm = "0.27"
tiny_http = "0.12.0"
eframe = "0.34.3"

[dev-dependencies]
tempfile = "3.8"

[[bin]]
name = "hyprlaunch"
path = "src/main.rs" 
